### ISSUE TITLE
Running geyser on a test validator

### ISSUE THREAD

**Issue by nevi-me** [rpcpool/yellowstone-grpc#131]
I'm trying to set up the geyser to run locally, I've followed instructions and cerated a gRPC Rust client, and all I get are pings every 10 seconds

```
SubscribeUpdate { filters: [], update_oneof: Some(Ping(SubscribeUpdatePing)) }
```

I'm using the v1.14 branch so that it matches my solana-* dep versions. I've added the default config (also tried a barebones grpc config with no filters set).

Is there something that I'm missing? We want to use the geyser on mainnet, so I want to test that our stuff works before we do that.

```sh
solana-test-validator \
        --geyser-plugin-config ./deps/geyser-config.json \
        --bpf-program ...
```

```json
{
    "libpath": "./libyellowstone_grpc_geyser.so",
    "log": {
        "level": "debug"
    },
    "grpc": {
        "address": "0.0.0.0:10000",
        "channel_capacity": "100000",
        "filters": {
            "accounts": {
                "max": 1,
                "any": false,
                "account_max": 10,
                "account_reject": [],
                "owner_max": 10,
                "owner_reject": [
                    "11111111111111111111111111111111"
                ]
            },
            "slots": {
                "max": 1
            },
            "transactions": {
                "max": 1,
                "any": false,
                "account_include_max": 10,
                "account_include_reject": [],
                "account_exclude_max": 10
            },
            "blocks": {
                "max": 1
            },
            "blocks_meta": {
                "max": 1
            }
        }
    }
}
```

----

The validator logs only show the below when I tail them. I had previously confirmed that the geyser does start up (I suppose I wouldn't get pings if it didn't work).

```sh
tail -f test-ledger/validator-*.log | grep geyser
[2023-05-25T13:24:44.166768161Z INFO  yellowstone_grpc_geyser::grpc] 1, new subscriber
[2023-05-25T13:24:44.166808477Z INFO  yellowstone_grpc_geyser::grpc] 1, add client to receivers
[2023-05-25T13:24:44.167568346Z INFO  yellowstone_grpc_geyser::grpc] 1, update client
```

My subscription payload is:

```js
{"filters": SubscribeRequestFilterAccounts { account: ["3DKYw5UA4VcZsb9b5L3gsNPxaojkFDUbcwyqacUum89w", "GVB4rC4FTSz5N5WqbvcJRqoZdBxke1xd5PLRDXbnangK", "CPihKkqoqsbkYeTqceVZs8WSiGD1Tzx3YtJ8iYzyCLtZ", "CZTCHgvxCoHrwQj7Gp27UHpfbTN8nfbEYpSwA2Ea5SP5", "Bs9j3Tgxg8UoUQQurpxfTq8cT7fExjoMUQS7Ffdv89YV", "4Z32gCVm6E7RCPMnwXaGRoBaK9wHpE4JY9xn9FYFS1zd", "B4k7fcZaCMAL3kGJcSYCnZ6F7Ej2iKDLzkvAmjiwcwcq"], owner: [], filters: [] }}
```

**Comment by fanatid** [comment]
In TOML config filters are used as limitations for filters passed by clients, so if it would not be public service you can skip this field in the config (this would mean no limit).
Can you try to subscribe on all accounts and check that you receive some data?

**Comment by fanatid** [comment]
Yes, to subscribe on all accounts you need to pass a config like this:
```
{"slots": { "slots": {} }, "accounts": { "my-filter-name": {} }, "transactions": {}, "blocks": {}, "blocks_meta": {}}
```
or you can use rust example from this repo:
```
cargo build -p yellowstone-grpc-client-simple --bin client && ./target/debug/client subscribe --accounts
```

**Comment by Arrowana** [comment]
> I've changed the config to the below, and then also subscribed to transactions and slots. Still getting only the pings.
> 
> ```json
> {
>     "libpath": "./libyellowstone_grpc_geyser.so",
>     "log": {
>         "level": "trace"
>     },
>     "grpc": {
>         "address": "0.0.0.0:10000",
>         "channel_capacity": "1000"
>     }
> }
> ```
> 
> How do I subscribe on all account? Send empty `accounts` and `account_filter` vecs? Trying that now.
> 
> EDIT: also not working. Maybe it just doesn't work on a test validator, as I don't know what else I could configure. Even with trace logs I don't see anything in the validator's logs beyond confirming that the geyser started and it's got a subscription request.

I wanted to do the same, i could see in the plugin manager that account updates are sent, but on the client side nothing ever gets received.

After adding some extra debug logs i can see that `startup_received` and `startup_processed_received` always remain false, as a result it never calls the callback in `with_inner`.

So i started to go up the call stack validator side from the `notify_end_of_startup` and it looks like it is all related to a code path from loading a snapshot, but when starting from genesis we might never call this?

To confirm this i started the test validator, let it run up to 100 slots to get a full snapshot. Then stopped it and started it again from its snapshot (default). Now those two variables are true and updates are being received from the yellowstone client O_o.

I think the bug is in this plugin but at the same time the interface isn't intuitive, the account updated are given with is_startup, notify_end_of_startup never fires when starting from genesis because there was indeed no startup phase then the plugin is stuck.

I think it might be worth fixing the genesis case as running the solana-test-validator reduce the iteration loop time.

**Comment by fanatid** [comment]
> To confirm this i started the test validator, let it run up to 100 slots to get a full snapshot.

Yes, I forgot to mention this, for correct work, we need a full snapshot which is available after 100 slots... :confused:
